import type { Metadata } from "next";
import { cookies } from 'next/headers';
import 'bootstrap/dist/css/bootstrap.min.css'
import "bootstrap-icons/font/bootstrap-icons.css"
import "@/app/globals.css";
import { checkUser } from "@/lib/checkUser";
import Script from 'next/script';
import Navbar from "../layouts/Navbar";
export const metadata: Metadata = {
  title: "Swwetyhortus",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {

  let user = null;
  try {
    const isAuthenticated = await checkUser();
    if(isAuthenticated){
      const cookieStore = await cookies();
      const cookieHeader = cookieStore.toString();

      const response = await fetch('http://localhost:3000/api/me', {
          cache: 'no-store',
          headers: {
              'Cookie': cookieHeader
          }
      });

      if (response.ok) {
          user = await response.json();
      }
    }
  } catch (error) {
      console.error('Erreur lors de la récupération de l\'utilisateur:', error);
  }

  return (
    <html lang="fr">
      <body>
        <Navbar user={user} />
        {children}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
        />
        </body>
    </html>
  );
}
